// Standard
import { AppProps } from "next/app";
import Head from "next/head";

// UI
import "../src/styles/global.css";

import { RecoilRoot } from "recoil";
// Custom
import RootLayout from "@/src/app/layout";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <RecoilRoot>
      <Head>
        <title>SecondOffice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" sizes="any" />
      </Head>
      <RootLayout>
        <Component {...pageProps} />
      </RootLayout>
    </RecoilRoot>
  );
}
export default MyApp;
